#!/usr/bin/env python3
"""Bundle versioned locale catalogs for an offline-capable static website."""
from pathlib import Path
import json

def build():
    root = Path(__file__).resolve().parent
    languages = ['en','ja']
    catalogs = {code: json.loads((root/'locales'/f'{code}.json').read_text(encoding='utf-8')) for code in languages}
    (root/'locales.js').write_text('// Generated by build_locales.py; edit locales/*.json.\nwindow.SloopLocales = '+json.dumps(catalogs,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
    return catalogs

if __name__ == '__main__': build()
