// SPDX-License-Identifier: GPL-3.0-only
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {mkdir,readFile} from 'node:fs/promises';
import {resolve,sep} from 'node:path';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(30000);
if(process.env.STUDIO_STATIC_DIR){
 const root=resolve(process.env.STUDIO_STATIC_DIR);
 await page.route('http://127.0.0.1:8769/**',async route=>{
  const pathname=decodeURIComponent(new URL(route.request().url()).pathname),path=resolve(root,'.'+pathname+(pathname.endsWith('/')?'index.html':''));
  if(!path.startsWith(root+sep))return route.fulfill({status:403,body:''});
  try{await route.fulfill({path});}catch{await route.fulfill({status:404,body:''});}
 });
}
await page.addInitScript(()=>{
 document.cookie='sloop_simulator_tour_v1=seen; Path=/; SameSite=Lax';
 navigator.requestMIDIAccess=()=>{throw Error('Unexpected hardware access');};
 const Context=window.AudioContext;window.AudioContext=class extends Context {createAnalyser(){const a=super.createAnalyser();window.testAnalyser=a;return a;}};
});
const button=name=>page.locator('.native-buttons').getByRole('button',{name,exact:true});
const exportSession=async()=>{const event=page.waitForEvent('download');await page.locator('#audio-export').click();return JSON.parse(await readFile(await (await event).path(),'utf8'));};
const signal=()=>page.waitForFunction(()=>{const a=new Float32Array(testAnalyser.fftSize);testAnalyser.getFloatTimeDomainData(a);return a.some(v=>Math.abs(v)>.001);});
try{
 await page.goto('http://127.0.0.1:8769/webapp/editor/',{waitUntil:'domcontentloaded',timeout:60000});
 await page.getByRole('button',{name:'Essential only',exact:true}).click();
 await page.locator('#view-firmware').click();await page.locator('.native-screen').waitFor({state:'visible'});
 const chooseLayout=async name=>{await page.getByRole('button',{name,exact:true}).click();};
 assert.equal(await page.locator('#firmware-view #play-keys button').count(),27);
 await chooseLayout('Expanded');
 await page.waitForFunction(()=>document.querySelector('.native-status').textContent.includes('Stopped'));
 assert.equal(await page.locator('.native-buttons button').count(),14);assert.equal(await page.locator('.native-dial').count(),8);
 assert.ok(await page.locator('#play-keys button').count()>27,'shared responsive key range');
 const checkDock=async()=>assert.ok(await page.locator('.play-keyboard').evaluate(e=>{const r=e.getBoundingClientRect();return Math.abs(r.left)<1&&Math.abs(r.right-innerWidth)<1&&Math.abs(r.bottom-innerHeight)<1;}),'keyboard spans viewport and stays at bottom');
 await checkDock();
 const panelLayout=await page.locator('.native-body').evaluate(e=>{const [left,screen,right]=[e.querySelector('.native-navigation'),e.querySelector('.native-display'),e.querySelector('.native-controls')].map(x=>x.getBoundingClientRect());return left.right<=screen.left&&screen.right<=right.left;});
 assert.ok(panelLayout,'FM-1 left controls / center screen / right controls');
 assert.equal(await page.locator('.native-encoder button').count(),8,'only knobs, no plus/minus buttons');
 const volume=Number(await page.locator('#audio-volume').inputValue());await page.getByRole('button',{name:'MASTER',exact:true}).press('ArrowUp');assert.equal(Number(await page.locator('#audio-volume').inputValue()),volume+1);
 const master=await page.getByRole('button',{name:'MASTER',exact:true}).boundingBox(),mx=master.x+master.width/2,my=master.y+master.height/2;
 await page.mouse.move(mx,my);await page.mouse.down();await page.mouse.move(mx,my-32,{steps:8});await page.mouse.up();
 assert.equal(Number(await page.locator('#audio-volume').inputValue()),volume+9,'normal drag');
 await page.keyboard.down('Shift');await page.mouse.move(mx,my);await page.mouse.down();await page.mouse.move(mx,my-32,{steps:8});await page.mouse.up();await page.keyboard.up('Shift');
 assert.equal(Number(await page.locator('#audio-volume').inputValue()),volume+10,'Shift drag is eight times finer');
 assert.ok(await page.locator('.native-screen').evaluate(c=>c.getContext('2d').getImageData(0,0,240,240).data.some((v,i)=>i%4!==3&&v>0)));
 const screenWidth=async()=>(await page.locator('.native-screen').boundingBox()).width;
 await chooseLayout('Device');const deviceWidth=await screenWidth();await chooseLayout('Expanded');assert.equal(await page.locator('#firmware-view').getAttribute('data-layout'),'expanded');
 assert.ok(await screenWidth()>deviceWidth*1.3,'Expanded visibly enlarges screen on desktop');
 await mkdir('build/screenshots',{recursive:true});await page.screenshot({path:'build/screenshots/simulator-expanded-desktop.png',fullPage:true});
 assert.equal(await page.locator('#tabs').isVisible(),false);
 const before=await exportSession();await button('ENV').click();
 await page.getByRole('button',{name:'KNOB 1',exact:true}).press('Shift+ArrowUp');
 const changed=await exportSession();assert.equal(changed.tracks[0].p[1],before.tracks[0].p[1]+1,'native encoder edit/export barrier');
 await page.locator('#browser-start').click();
 await page.waitForFunction(v=>document.querySelector('#groups input[aria-label=ATK]')?.value===String(v),changed.tracks[0].p[1]);
 await page.locator('#view-firmware').click();
 await page.evaluate(()=>document.activeElement?.blur());await page.keyboard.down('a');await signal();await page.keyboard.up('a');
 console.log('Native canvas, encoders, shared state and QWERTY audio passed');
 const key=id=>page.locator(`#play-keys [data-note="${53+id}"]`);
 await page.locator('#play-keys').scrollIntoViewIfNeeded();
 const point=async(id,black=false)=>{const b=await key(id).boundingBox();return {x:b.x+b.width/2,y:b.y+b.height*(black?.3:.85)};};
 const a=await point(0),b=await point(2),sharp=await point(1,true);
 await page.keyboard.down('a');await page.mouse.move(a.x,a.y);await page.mouse.down();
 await page.mouse.move(b.x,b.y,{steps:8});
 assert.equal(await key(0).getAttribute('aria-pressed'),'true','QWERTY owner survives pointer slide');
 assert.equal(await key(2).getAttribute('aria-pressed'),'true');
 await page.keyboard.up('a');assert.equal(await key(0).getAttribute('aria-pressed'),'false');
 await page.mouse.move(sharp.x,sharp.y,{steps:8});assert.equal(await key(1).getAttribute('aria-pressed'),'true','slide onto black key');
 assert.equal(await key(2).getAttribute('aria-pressed'),'false');
 await page.mouse.move(a.x,a.y+100);assert.equal(await page.locator('#play-keys [aria-pressed=true]').count(),0,'leaving keys releases note');
 await page.mouse.move(b.x,b.y);assert.equal(await key(2).getAttribute('aria-pressed'),'true','drag can re-enter keys');
 await page.mouse.up();assert.equal(await page.locator('#play-keys [aria-pressed=true]').count(),0);
 const touch=await page.context().newCDPSession(page);
 const send=points=>touch.send('Input.dispatchTouchEvent',{type:points.length?'touchMove':'touchEnd',touchPoints:points});
 await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:10},{...b,id:11}]});
 assert.equal(await page.locator('#play-keys [aria-pressed=true]').count(),2);
 await send([{...b,id:10},{...b,id:11}]);assert.equal(await key(0).getAttribute('aria-pressed'),'false');
 assert.equal(await key(2).getAttribute('aria-pressed'),'true','two fingers can share a note');
 await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[{...b,id:10}]});
 assert.equal(await key(2).getAttribute('aria-pressed'),'true','lifting one finger preserves the other');
 await touch.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
 assert.equal(await page.locator('#play-keys [aria-pressed=true]').count(),0,'touch cancellation releases notes');
 await touch.detach();console.log('Native mouse/touch sliding, black keys, re-entry and shared note ownership passed');
 await page.getByRole('button',{name:'Minimize keyboard',exact:true}).click();
 assert.equal(await page.locator('#play-keys').isVisible(),false);
 await page.getByRole('button',{name:'Show keyboard',exact:true}).click();
 assert.equal(await page.locator('#play-keys').isVisible(),true);
 await page.locator('#play-octave').selectOption('4');
 await page.waitForFunction(()=>document.querySelector('#play-keys [data-note="65"] small')?.textContent==='A');
 await button('OCT−').click();await page.waitForFunction(()=>document.querySelector('#play-octave').value==='3');
 await button('SEQ').focus();await page.keyboard.down('Space');await page.keyboard.press('a');await page.keyboard.up('Space');
 assert.ok((await exportSession()).tracks[0].step[0].n,'shared keyboard enters native steps');
 await button('SEQ').focus();await page.keyboard.down('Space');await page.keyboard.press('a');await page.keyboard.up('Space');
 assert.equal((await exportSession()).tracks[0].step[0].n,0,'shared keyboard toggles native step off');
 await button('REC').click();await page.waitForFunction(()=>document.querySelector('.native-status').textContent.includes('armed'));
 await page.keyboard.down('a');await page.waitForTimeout(1300);await page.keyboard.up('a');await button('REC').click();
 await page.waitForFunction(()=>document.querySelector('.native-status').textContent.includes('Playing'));
 await page.locator('#audio-stop').click();const recorded=await exportSession();assert.ok(recorded.tracks[0].step.some(s=>s.n),'real free recording');
 await button('FX').focus();await page.keyboard.down('Space');await page.waitForTimeout(200);
 await page.keyboard.down('a');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.keyboard.up('a');await page.keyboard.up('Space');
 await page.waitForFunction(()=>!document.querySelector('.native-buttons [aria-pressed=true]')&&!document.querySelector('#play-keys [aria-pressed=true]'));
 await page.waitForFunction(()=>document.querySelector('.native-status').textContent.includes('Layer PLAY'));
 await button('ENV').click();await page.waitForTimeout(100);await button('SAVE').click();await page.waitForTimeout(100);await button('SAVE').click();await page.waitForTimeout(100);
 await page.getByRole('button',{name:'KNOB 4',exact:true}).press('ArrowUp');await page.getByRole('button',{name:'KNOB 4',exact:true}).press('ArrowUp');
 const banked=await exportSession();assert.ok(banked.bank[0],'native user bank saved on audio thread');
 console.log('Native free recording and focus-loss release passed');
 await page.setViewportSize({width:390,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile fits');await checkDock();
 await chooseLayout('Device');const mobileWidth=await screenWidth();await chooseLayout('Expanded');assert.ok(await screenWidth()>mobileWidth*1.5,'Expanded enlarges screen on mobile');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'build/screenshots/simulator-expanded-mobile.png',fullPage:true});
 await chooseLayout('Device');
 await mkdir('build/screenshots',{recursive:true});await page.screenshot({path:'build/screenshots/native-firmware-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1100});await button('HOME').click();await page.waitForTimeout(100);
 await page.screenshot({path:'build/screenshots/native-firmware-desktop.png',fullPage:true});
 await page.locator('#device-mode').click();await page.locator('#firmware-view').waitFor({state:'hidden'});
 await page.reload({waitUntil:'domcontentloaded'});await page.locator('#view-firmware').click();await page.locator('.native-screen').waitFor({state:'visible'});
 const restored=await exportSession();assert.deepEqual(restored.tracks[0].step,recorded.tracks[0].step);assert.deepEqual(restored.native,recorded.native);
 assert.deepEqual(restored.bank,banked.bank,'native user bank survives reload');
 page.on('dialog',d=>d.accept());
 const imported=structuredClone(restored);imported.tracks[0].p[1]=67;
 await page.locator('#audio-file').setInputFiles({name:'session.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});
 await page.waitForFunction(()=>document.querySelector('#groups input[aria-label=ATK]')?.value==='67');
 await page.locator('#view-firmware').click();assert.equal((await exportSession()).tracks[0].p[1],67);
 assert.deepEqual(errors,[]);console.log('Native mobile, session reload/import/export and mode switching passed');
}catch(error){console.error('Editor status:',await page.locator('#status').textContent(),errors);await page.screenshot({path:'build/native-failure.png',fullPage:true});throw error;}finally{await browser.close();}
